name: 🧠 Brainrot Gist Scanner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    name: 🚀 Запуск Системы
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🐍 Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Установка библиотек
        run: |
          pip install discord.py-self requests

      - name: 🛰️ Запуск мониторинга
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py

